### ISSUE TITLE
Investigar - JUnit

### ISSUE THREAD

**Issue by andres174** [andres174/proyecto-devops#4]
Investigar JUnit para la etapa de pruebas

**Comment by bermeo2000** [comment]
HOLA

**Comment by bermeo2000** [comment]
https://www.youtube.com/watch?v=v_w7pSWeQiM&list=WL&index=2

**Comment by bermeo2000** [comment]
JUnit se trata de un Framework Open Source para la automatización de las pruebas (tanto unitarias, como de integración) en los proyectos Software. El framework provee al usuario de herramientas, clases y métodos que le facilitan la tarea de realizar pruebas en su sistema y así asegurar su consistencia y funcionalidad.

**Comment by bermeo2000** [comment]
https://www.youtube.com/watch?v=1k22KuD4si0

**Comment by bermeo2000** [comment]
https://www.youtube.com/watch?v=3bhOlDIpz8A

**Comment by bermeo2000** [comment]
sabes que JUnit es como que se este utilizando java

**Comment by bermeo2000** [comment]
https://www.youtube.com/watch?v=EOkoVm3rtNQ&list=PLTd5ehIj0goML37B7s9I9iN2zhJCfxJBC

**Comment by bermeo2000** [comment]
https://www.youtube.com/watch?v=KkYVnj0k6Sw
