### ISSUE TITLE
Investigar - GitLab

### ISSUE THREAD

**Issue by andres174** [andres174/proyecto-devops#5]
Investigar GitLab para la etapa de release

**Comment by Arqui9897** [comment]
https://about.gitlab.com/

Básicamente es una plataforma para todo los pasos que se tiene que hacer en DevOps es un todo en uno que hubiera servidor para la gran mayoría en todos los pasos de este proyecto 


![image](https://user-images.githubusercontent.com/87206394/197646086-f652c065-dc52-4e1a-9832-2eaaa9d69bac.png)

###  es de _**pago**_ 
pero hay una prueba de 30 dias con la que podemos hacer la Implementacion del proyecto 

![image](https://user-images.githubusercontent.com/87206394/197646849-17f8da85-7653-4671-9b79-6bb637efee7f.png)



_esperando actualización de que hacer para ir avanzado_ 

### video de referencia


[![Alt text](https://img.youtube.com/vi/EscDe0jG6XM/0.jpg)](https://www.youtube.com/watch?v=EscDe0jG6XM)
