### ISSUE TITLE
Investigar - Puppet 

### ISSUE THREAD

**Issue by andres174** [andres174/proyecto-devops#7]
Investigar Puppet para la etapa de operate

**Comment by Arqui9897** [comment]
https://puppet.com/
![image](https://user-images.githubusercontent.com/87206394/197651197-8473a4ba-3ffd-4b99-aa63-d8f4b74d8f20.png)


no entiendo bien pero es para configurar y cuidar difernetes servidores sin importan el idioma que esten implementado 

https://www.youtube.com/watch?v=llcjg1R0DdM


_nose puppet es un poco raro hasta ahora lo que entiendo_

**Comment by Arqui9897** [comment]
mirando un poco más de información puppet es para automatizar ,organizar y configurar varios servidores desde un lugar centralizado

**Comment by Arqui9897** [comment]
### Operar
Gestiona la prestación integral de servicios de TI a los clientes. Esto incluye las prácticas relacionadas con el diseño, la implementación, la configuración y el mantenimiento de toda la infraestructura de TI que sirve de soporte a los servicios de una organización.

fuente: https://www.atlassian.com/es/devops

**Comment by Arqui9897** [comment]
bueno a la final me da ganas de matarme
