### ISSUE TITLE
Investigar - Splunk

### ISSUE THREAD

**Issue by andres174** [andres174/proyecto-devops#8]
Investigar Splunk para la fase de monitoreo

**Comment by Arqui9897** [comment]
https://www.splunk.com/

vale en pocas palabras splunk es una herramienta para visualizar metricas o datos de todo tipo de forma mas visual para poder ver que esta pasando exactamente con los deploy 

![image](https://user-images.githubusercontent.com/87206394/198843043-d9ccbaaa-b281-444e-85b5-6cdde679a84c.png)

en este caso encontré la pagina para poder integrar splunk con heroku y poder ver las metricas de mejor forma y ver que esta pasando en tras bastidores.

https://www.splunk.com/en_us/blog/tips-and-tricks/splunking-heroku.html

básicamente un dashboard para visualizar datos importantes y tomar decisiones
